name: CI

env:
  VERSION_GO: '1.19'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build & Test"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.VERSION_GO }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: nolar/setup-k3d-k3s@v1.0.8

      - name: Run unit tests
        run: make
